version: '3.8'

services:
  blog:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - TINACLIENTID
        - TINATOKEN
    container_name: hugo-blog
    ports:
      - "4321:4321"
    restart: unless-stopped 